import assert from "node:assert/strict";
import { filterHATools, haToolName, isHALlmTool, renderHAToolCard } from "../custom_components/extended_openai_conversation_responses/frontend/ha-llm-tools.js";
import { categorizeFunctionTools, synchronizePersistedFunctions } from "../custom_components/extended_openai_conversation_responses/frontend/agent-config-editor.js";

const tool = {spec: {name: "ha_reference_id"}, function: {type: "ha_llm", tool_name: "native_tool", source_id: "source", api_id: "assist"}, enabled: true};
const panel = {_e: value => String(value).replaceAll("<", "&lt;").replaceAll('"', "&quot;"), _haCatalog: {saved: {ha_reference_id: {available: false, source: "source <unsafe>", description: "Unavailable"}}}};
assert.equal(isHALlmTool(tool), true);
assert.equal(haToolName(tool), "native_tool");
const card = renderHAToolCard(panel, tool, 0);
assert.match(card, /native_tool/);
assert.match(card, /Unavailable/);
assert.match(card, /Remove/);
assert.match(card, /tool-enabled/);
assert.match(card, /&lt;unsafe>/);
assert.doesNotMatch(card, /edit-tool|duplicate-tool|YAML/);
assert.match(renderHAToolCard(panel, {...tool, enabled: false}, 1), /is-disabled/);
const catalog = [{name: "First", description: "Weather", source: "One", already_added: true}, {name: "Second", description: "Weather", source: "Two"}, {name: "Third", description: "Lights", source: "Two"}];
assert.deepEqual(filterHATools(catalog, "weather", ["Two"]), [catalog[1]]);
assert.deepEqual(filterHATools(catalog, "", ["One", "Two"]), catalog);
assert.deepEqual(filterHATools(catalog, "unknown"), []);
const groups = [{id: "remote", name: "Remote", description: "Remote", loading_mode: "on_demand", enabled: true, functions: [tool.spec.name]}];
const categorized = categorizeFunctionTools({functions: [tool], function_groups: groups});
assert.equal(categorized.alwaysAvailable.length, 0);
assert.equal(categorized.groups.length, 1);
const syncPanel = {_configData: {config: {prompt: "saved"}}, _draft: {prompt: "unsaved"}, _syncConfigDirty() { this.synced = true; }};
synchronizePersistedFunctions(syncPanel, {functions: [tool], function_groups: groups});
assert.deepEqual(syncPanel._draft.functions, [tool]);
assert.equal(syncPanel._draft.prompt, "unsaved");
assert.equal(syncPanel.synced, true);
