import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {reconcileKeyedChildren, keyedElement} from "../custom_components/extended_openai_conversation_responses/frontend/keyed-collection.js";
const base = new URL("../custom_components/extended_openai_conversation_responses/", import.meta.url);
const read = path => readFile(new URL(path, base), "utf8");
const panel = await read("frontend/management-panel.js");
const route = await read("frontend/management-route.js");
const memory = await read("frontend/guest-mode-ui.js");
const temporary = await read("frontend/management-temporary-memory.js");
const knowledge = await read("frontend/management-knowledge-feature.js");
assert.doesNotMatch(panel, /import .*from "\.\/(?:guest-mode-ui|management-knowledge-feature|management-memory-feature|management-temporary-memory)\.js"/);
assert.match(route, /"data-memory\/knowledge": \(\) => import\("\.\/management-knowledge-feature.js"\)/);
assert.match(route, /"data-memory\/memories": \(\) => import\("\.\/management-memory-feature.js"\)/);
assert.match(panel, /getRouteFeature\(view\)\?\.reconcileKnowledge\(this\)/);
assert.match(panel, /getRouteFeature\(view\)\?\.reconcileMemories\(this\)/);
for (const owner of [memory, temporary, knowledge, await read("frontend/memory-panel.js")]) assert.match(owner, /from "\.\/keyed-collection.js"/);
assert.match(await read("memory_ui.py"), /f"\/{DOMAIN}\/keyed-collection.js"/);
assert.match(knowledge, /source => source.source_id/);
assert.match(memory, /memory => memory.memory_id/);
assert.match(temporary, /memory => memory.memory_id/);
// Node factories are supported without changing the markup-factory contract.
const records = new Map();
const node = {};
assert.equal(keyedElement(records, "one", "a", () => node).node, node);
assert.equal(keyedElement(records, "one", "a", () => { throw Error("unchanged card rendered"); }).node, node);
assert.notEqual(keyedElement(records, "one", "b", () => ({})).node, node);
assert.equal(typeof reconcileKeyedChildren, "function");
