"""Real-HA acceptance for a config update racing an in-flight conversation."""

from __future__ import annotations

import asyncio
from typing import Any

import pytest

from custom_components.extended_openai_conversation_responses.const import (
    API_MODE_CHAT_COMPLETIONS,
    CONF_API_MODE,
    CONF_CHAT_MODEL,
)
from custom_components.extended_openai_conversation_responses.conversation import (
    ExtendedOpenAIAgentEntity,
)
from homeassistant.components import conversation
from homeassistant.config_entries import ConfigEntryState
from homeassistant.core import Context, HomeAssistant
from homeassistant.helpers import entity_registry as er
from tests_real_ha.test_acceptance_lifecycle import _make_entry, _setup_entry
from tests_real_ha.test_provider_wire_e2e import (
    _chat_sse_text,
    _install_wire,
    _speech,
)

_WAIT_TIMEOUT = 10
_OLD_MODEL = "gpt-5.6"
_NEW_MODEL = "gpt-4.1-mini"


def _conversation_subentry(entry):
    return next(
        subentry
        for subentry in entry.subentries.values()
        if subentry.subentry_type == "conversation"
    )


def _agent(hass: HomeAssistant, entry) -> ExtendedOpenAIAgentEntity:
    agent = conversation.async_get_agent(hass, entry.entry_id)
    assert isinstance(agent, ExtendedOpenAIAgentEntity)
    return agent


def _current_text(log: conversation.ChatLog) -> str:
    return next(
        item.content
        for item in reversed(log.content)
        if isinstance(getattr(item, "content", None), str)
    )


async def _converse(
    hass: HomeAssistant,
    entry,
    text: str,
) -> conversation.ConversationResult:
    return await conversation.async_converse(
        hass=hass,
        text=text,
        conversation_id=None,
        context=Context(),
        language="en",
        agent_id=entry.entry_id,
    )


@pytest.mark.asyncio
async def test_config_update_reload_isolates_inflight_request_and_uses_new_model(
    hass: HomeAssistant,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A live config update replaces the agent without poisoning an old request."""
    entry = _make_entry(
        "In-flight config update",
        include_ai_task=False,
        conversation_options={
            CONF_API_MODE: API_MODE_CHAT_COMPLETIONS,
            CONF_CHAT_MODEL: _OLD_MODEL,
        },
    )
    await _setup_entry(hass, entry)
    old_agent = _agent(hass, entry)
    old_subentry = _conversation_subentry(entry)
    assert old_subentry.data[CONF_CHAT_MODEL] == _OLD_MODEL

    entered = asyncio.Event()
    release = asyncio.Event()

    async def blocking_model(log: conversation.ChatLog, **kwargs: Any) -> None:
        del kwargs
        current = _current_text(log)
        entered.set()
        await release.wait()
        log.async_add_assistant_content_without_tools(
            conversation.AssistantContent(
                agent_id=old_agent.entity_id,
                content=f"old-generation:{current}",
            )
        )

    monkeypatch.setattr(old_agent, "_async_handle_chat_log", blocking_model)

    old_request = asyncio.create_task(
        _converse(hass, entry, "request crossing config update")
    )
    await asyncio.wait_for(entered.wait(), timeout=_WAIT_TIMEOUT)
    assert not old_request.done()

    updated_data = dict(old_subentry.data)
    updated_data[CONF_CHAT_MODEL] = _NEW_MODEL
    hass.config_entries.async_update_subentry(
        entry,
        old_subentry,
        data=updated_data,
    )

    # The integration's real update listener reloads the parent entry. The old
    # request must not block that replacement runtime from becoming available.
    await asyncio.wait_for(hass.async_block_till_done(), timeout=_WAIT_TIMEOUT)
    assert entry.state is ConfigEntryState.LOADED
    new_agent = _agent(hass, entry)
    assert new_agent is not old_agent
    assert not old_request.done()

    new_subentry = _conversation_subentry(entry)
    assert new_subentry.subentry_id == old_subentry.subentry_id
    assert new_subentry.data[CONF_CHAT_MODEL] == _NEW_MODEL
    assert new_agent.subentry.data[CONF_CHAT_MODEL] == _NEW_MODEL

    # Prove the replacement runtime consumes the saved configuration rather than
    # merely observing updated storage: exercise the real OpenAI SDK serialization
    # seam and inspect the provider request generated by the fresh agent.
    wire = _install_wire(
        monkeypatch,
        new_agent,
        [_chat_sse_text("fresh generation uses the updated model")],
    )
    fresh = await _converse(hass, entry, "fresh request after config update")
    assert _speech(fresh) == "fresh generation uses the updated model"
    assert len(wire.requests) == 1
    assert wire.requests[0]["path"] == "/v1/chat/completions"
    assert wire.requests[0]["body"]["model"] == _NEW_MODEL
    assert not old_request.done()

    # Allow the stale generation to finish afterwards. Completing an old request
    # must not re-register or otherwise resurrect its unloaded agent.
    release.set()
    old_result = await asyncio.wait_for(old_request, timeout=_WAIT_TIMEOUT)
    assert _speech(old_result) == "old-generation:request crossing config update"
    assert conversation.async_get_agent(hass, entry.entry_id) is new_agent

    rows = [
        row
        for row in er.async_entries_for_config_entry(er.async_get(hass), entry.entry_id)
        if row.domain == "conversation"
    ]
    assert len(rows) == 1
    assert rows[0].config_subentry_id == new_subentry.subentry_id
    assert rows[0].entity_id == new_agent.entity_id
