name: hacs

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@11d5960a326750d5838078e36cf38b85af677262" # v4
        - uses: "home-assistant/actions/hassfest@a7c616ce81ccda50150bf1595786c71b1883fabb" # master
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26" # v3
      - name: HACS validation
        uses: "hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa" # main
        with:
          category: "integration"